### ISSUE TITLE
Très jolie

### ISSUE THREAD

**Issue by MelvynX** [Wafiki789/jeutroppro#1]
Je viens de tester ton jeu trop cool. 

Bravo, c'est super sympa ! J'ai vue que tu étais français :o 

Je trouve ça dommage, m'ayant intéressé au code de ton site, que tu écrives l’intégralité du JavaScript sur ta page **main** html...

C'est un peu illisible et si tu veut l'améliorer, tu vas galéré.

Je te conseille de partager un peu ton fichier pour mieux pouvoir le comprendre.

Et sinon, malgré quelque beug c'est super sympa ! 

Bonne fin de journée

**Comment by Wafiki789** [comment]
Merci d'avoir pris le temps de jouer à mon jeu et d'avoir écrit un commentaire :) Contente que le jeu t'ait plu!

Je suis effectivement francophone, mais québécoise! 

C'était mon tout premier projet de programmation il y a maintenant 5 ans de ça (wow, le temps passe vite!). Je suis pas surprise qu'il y ait des atrocités dans le code et de mauvaises pratiques de programmation. 

C'est cependant un projet que j'ai arrêté il y a longtemps (c'est un prototype que je considère complet), alors je ne pense pas y revenir pour rendre le code plus clean ^^" J'ose espérer m'être améliorée depuis. J'ai fait très peu de jeux en HTML depuis, j'ai migré vers Unity et d'autres tools plus commodes. 

Je serais curieuse d'entendre quels sont ces bugs :O La dernière fois que j'y ai touché, il y a 3 ans, je pensais avoir pas mal tout fixé. Oh well!

**Comment by MelvynX** [comment]
Alors je suis heureux de ne pas avoir pris le temps de te lâcher un com pour rien 😮

Tu dis ne pas faire beaucoup de html, mais je vois beaucoup de projet HTML sur ton git, après tu ne met peux être pas tes projets Unix sur GitHub. 
Et d’ailleurs, je viens de découvrir ton projet https://github.com/Wafiki789/TicTacToe-Javascript- que je viens de tester avec l'IA, bravo ahah 
J'avais voulu faire une IA en TicTacToe mais j'avais abandonner car je pensais que c’était rapide à faire 😂

Voici les deux petit beug que j'ai trouvé (dans le menu règle):
Le premier est qu'il est impossible de retourner dans le menu d'accueil 

Le deuxième et qu'on ne voit pas la liste des règles affiché complètement.
<img width="1680" alt="Capture d’écran 2020-02-24 à 19 16 22" src="https://user-images.githubusercontent.com/56388157/75179465-702df080-573a-11ea-8209-08786653f062.png">

Je te souhaite une bonne soirée depuis la Suisse 🇨🇭
